# Generated by Django 5.2.7 on 2025-12-27 11:21

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the player.', primary_key=True, serialize=False)),
                ('current_level', models.PositiveIntegerField(default=1, help_text='Current level in the active run.')),
                ('high_score', models.PositiveIntegerField(default=0, help_text='All-time highest score achieved.')),
                ('is_guest', models.BooleanField(default=False, help_text='Whether this is a temporary guest account.')),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('tr', 'Türkçe')], default='en', help_text='Preferred language for the game interface.', max_length=5)),
                ('total_games_played', models.PositiveIntegerField(default=0, help_text='Total number of game runs started.')),
                ('total_games_won', models.PositiveIntegerField(default=0, help_text='Total number of levels successfully completed.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when account was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when account was last updated.')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'ordering': ['-high_score', '-current_level'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the game session.', primary_key=True, serialize=False)),
                ('board_state', models.JSONField(blank=True, default=dict, help_text='JSON representation of the game board state.')),
                ('level_number', models.PositiveIntegerField(default=1, help_text='Current level number in this run.')),
                ('clues_remaining', models.PositiveIntegerField(default=1, help_text="Number of 'Clue' power-ups remaining for this level.")),
                ('score', models.PositiveIntegerField(default=0, help_text='Accumulated score for this run.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('won', 'Won'), ('lost', 'Lost'), ('abandoned', 'Abandoned')], default='active', help_text='Current status of the game session.', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this session is currently active.')),
                ('time_elapsed', models.PositiveIntegerField(default=0, help_text='Total time elapsed in seconds.')),
                ('cells_revealed', models.PositiveIntegerField(default=0, help_text='Number of cells revealed in this session.')),
                ('flags_placed', models.PositiveIntegerField(default=0, help_text='Number of flags currently placed.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when session was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when session was last updated.')),
                ('player', models.ForeignKey(help_text='The player who owns this session.', on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Game Session',
                'verbose_name_plural': 'Game Sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the score record.', primary_key=True, serialize=False)),
                ('level_reached', models.PositiveIntegerField(db_index=True, default=1, help_text='Highest level reached in this run.')),
                ('final_score', models.PositiveIntegerField(db_index=True, default=0, help_text='Total score achieved in this run.')),
                ('time_taken', models.PositiveIntegerField(default=0, help_text='Total time taken in seconds.')),
                ('cells_revealed_total', models.PositiveIntegerField(default=0, help_text='Total cells revealed across all levels.')),
                ('clues_used', models.PositiveIntegerField(default=0, help_text='Total clues used during the run.')),
                ('was_victory', models.BooleanField(default=False, help_text='Whether the run ended in victory (vs game over).')),
                ('completed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Timestamp when this run was completed.')),
                ('player', models.ForeignKey(help_text='The player who achieved this score.', on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(blank=True, help_text='Reference to the original game session.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_score', to='game.gamesession')),
            ],
            options={
                'verbose_name': 'Score',
                'verbose_name_plural': 'Scores',
                'ordering': ['-final_score', '-level_reached', 'time_taken'],
            },
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['player', 'is_active'], name='game_gamese_player__13bb84_idx'),
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['status'], name='game_gamese_status_f1e5b9_idx'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['player', '-final_score'], name='game_score_player__d003f6_idx'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['-final_score', '-level_reached'], name='game_score_final_s_4569d1_idx'),
        ),
    ]
